<Header> This is is where we develop a baseline factor model that allows us to take certain factors and use them in multi-OLS regression to predict our excess return signals on a security level. These signals are absolute. </Header>

In [1]:
#First, import our packages for the database connection and dataframe access
import mysql.connector
import pandas as pd
import statsmodels.api as sm
import numpy as np
import warnings
from datetime import datetime, timedelta

In [2]:
#Ignore warnings and set max row display option
warnings.filterwarnings("ignore")
pd.set_option('display.min_rows', 300)

In [3]:
# Connect to MySQL database
connection = mysql.connector.connect(
    host="ubctg.con7266gcvin.us-east-2.rds.amazonaws.com",
    user="admin",
    password="ubctgquant",
    database="ubctg"
)

Here, we pull monthly returns across the stock universe over 10 years from 2011 to 2021

In [4]:
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

# Define the start and end dates
start_date = '2017-12-01'
end_date = '2021-01-31'

# SQL query to retrieve data from the "Volatility" table between two dates
sql_query = f"SELECT * FROM `Monthly Returns` mr WHERE Date BETWEEN '{start_date}' AND '{end_date}'"

# Execute the SQL query
cursor.execute(sql_query)

# Fetch all rows from the result set
universe_data = cursor.fetchall()

# Convert fetched data into a pandas DataFrame
columns = [i[0] for i in cursor.description]  # Extract column names from cursor description

#create new df
universe_df = pd.DataFrame(universe_data, columns=columns)

#close cursor and db connection
cursor.close()

True

Generate the number of observations per security in our table. This way we can remove those that do not have a full dataset

In [5]:
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

# Define the start and end dates
start_date = '2017-12-01'
end_date = '2021-01-31'

# SQL query to retrieve data from the "Volatility" table between two dates
sql_query = f"SELECT COUNT(PERMNO), PERMNO FROM `Monthly Returns` mr WHERE Date BETWEEN '{start_date}' AND '{end_date}' GROUP BY PERMNO"

# Execute the SQL query
cursor.execute(sql_query)

# Fetch all rows from the result set
observationTable_data = cursor.fetchall()

# Convert fetched data into a pandas DataFrame
columns = [i[0] for i in cursor.description]  # Extract column names from cursor description

#create new df
observation_df = pd.DataFrame(observationTable_data, columns=columns)

#close cursor and db connection
cursor.close()

True

Here, we remove securities that do not have enough observations (in our case, we look for at least 120)

In [6]:
#Filter securities with at least median observations in the period. This is not a great way to eliminate observations, so I would be cautious in doing this. There are better ways to filter out insufficient data
observation_df_filtered = observation_df[pd.to_numeric(observation_df['COUNT(PERMNO)']) >= int(pd.to_numeric(observation_df['COUNT(PERMNO)']).median())]

#Inner join our dataframes to only keep the securities we have data on
universe_df_filtered = pd.merge(universe_df, observation_df_filtered, on='PERMNO', how='inner')

We can now add our consumer sentiment factor to our model. We then join it to our monthly returns dataframe for our OLS regression

In [7]:
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

# Define the start and end dates
start_date = '2017-12-01'
end_date = '2021-01-31'

# SQL query to retrieve data from the "Volatility" table between two dates
sql_query = f"SELECT * FROM `Consumer_Sentiment` mr WHERE Date BETWEEN '{start_date}' AND '{end_date}'"

# Execute the SQL query
cursor.execute(sql_query)

# Fetch all rows from the result set
observationTable_data = cursor.fetchall()

# Convert fetched data into a pandas DataFrame
columns = [i[0] for i in cursor.description]  # Extract column names from cursor description

#create new df
sentiment_df = pd.DataFrame(observationTable_data, columns=columns)

#close cursor and db connection
cursor.close()

True

In [8]:
#These dates are at the beginning of month, so we will operate on our monthly return dataframe to convert our dates to the beginning of the month so that we can append on index
universe_df_filtered["date"] = pd.to_datetime(universe_df_filtered["date"]).dt.to_period('M').dt.to_timestamp()

sentiment_df["date"] = pd.to_datetime(sentiment_df["DATE"])
sentiment_df = sentiment_df.drop('DATE', axis=1)

#Inner-join macro factors dataframe with universe dataframe, using 'date' column as index
universe_df_with_external_factors = pd.merge(universe_df_filtered, sentiment_df, on= 'date', how='inner')

display(universe_df_with_external_factors)

,PERMNO,date,COMNAM,NAICS,PERMCO,DCLRDT,DLPDT,PAYDT,RCRDDT,FACPR,...,ACPERM,ACCOMP,DLPRC,PRC,VOL,RET,BID,ASK,COUNT(PERMNO),UMCSENT
0,10026,2017-12-01,J & J SNACK FOODS CORP,311821,7976,2017-11-29,,2018-01-04,2017-12-13,0.0,...,,,NaN,151.83000,11819.0,0.007743,151.69000,151.83000,38,95.9
1,10028,2017-12-01,D G S E COMPANIES INC,448310,7978,,,,,NaN,...,,,NaN,0.93100,5076.0,-0.104808,0.93100,0.95000,38,95.9
2,10032,2017-12-01,PLEXUS CORP,334412,7980,,,,,NaN,...,,,NaN,60.72000,27640.0,-0.028635,60.69000,60.70000,38,95.9
3,10044,2017-12-01,ROCKY MOUNTAIN CHOC FAC INC NEW,311351,7992,,,,,NaN,...,,,NaN,11.77940,1316.0,0.024296,11.76000,11.80000,38,95.9
4,10051,2017-12-01,HANGER INC,339113,7999,,,,,NaN,...,,,NaN,NaN,NaN,B,NaN,NaN,38,95.9
5,10065,2017-12-01,ADAMS EXPRESS CO,525990,20023,,,,,NaN,...,,,NaN,15.03000,58124.0,0.010760,15.03000,15.04000,38,95.9
6,10066,2017-12-01,FRANKLIN WIRELESS CORP,,6331,,,,,NaN,...,,,NaN,NaN,NaN,B,NaN,NaN,38,95.9
7,10104,2017-12-01,ORACLE CORP,511210,8045,,,,,NaN,...,,,NaN,47.28000,3645284.0,-0.036282,47.29000,47.30000,38,95.9
8,10107,2017-12-01,MICROSOFT CORP,511210,8048,,,,,NaN,...,,,NaN,85.54000,4663253.0,0.016277,85.59000,85.60000,38,95.9
9,10113,2017-12-01,ADVISORSHARES TRUST,525990,53202,2017-12-26,,2017-12-29,2017-12-28,0.0,...,,,NaN,58.85000,5841.0,0.056049,58.80000,58.82000,38,95.9
10,10138,2017-12-01,T ROWE PRICE GROUP INC,523930,8087,2017-10-25,,2017-12-28,2017-12-14,0.0,...,,,NaN,104.93000,301523.0,0.025068,104.93000,104.94000,38,95.9
11,10145,2017-12-01,HONEYWELL INTERNATIONAL INC,423990,22168,,,,,NaN,...,,,NaN,153.36000,592689.0,-0.016671,153.67000,153.67999,39,95.9
12,10158,2017-12-01,AMERESCO INC,541611,53454,,,,,NaN,...,,,NaN,8.60000,10165.0,0.011765,8.55000,8.60000,38,95.9
13,10200,2017-12-01,REPLIGEN CORP,325414,8135,,,,,NaN,...,,,NaN,36.28000,64469.0,0.023413,36.27000,36.28000,38,95.9
14,10201,2017-12-01,ATLANTIC POWER CORP,221118,53455,,,,,NaN,...,,,NaN,2.35000,77777.0,-0.078431,2.35000,2.40000,38,95.9
15,10207,2017-12-01,SPROTT FOCUS TRUST INC,525990,9806,2017-12-05,,2017-12-28,2017-12-15,0.0,...,,,NaN,7.92000,10851.0,0.020050,7.92000,7.94000,38,95.9
16,10220,2017-12-01,B W X TECHNOLOGIES INC,332313,53456,,,,,NaN,...,,,NaN,60.49000,88560.0,-0.031385,60.49000,60.50000,38,95.9
17,10232,2017-12-01,ELMIRA SAVINGS BANK NY,522110,8158,2017-11-22,,2017-12-15,2017-12-08,0.0,...,,,NaN,20.44990,981.0,0.003879,20.25000,20.45000,39,95.9
18,10239,2017-12-01,BALDWIN & LYONS INC,524126,714,,,,,NaN,...,,,NaN,23.95000,3369.0,-0.018443,23.90000,23.95000,38,95.9
19,10252,2017-12-01,INDEPENDENT BANK CORP MA,522110,8179,2017-12-14,,2018-01-05,2017-12-26,0.0,...,,,NaN,69.85000,15461.0,-0.034801,69.80000,69.85000,38,95.9
20,10253,2017-12-01,DOCUMENT SECURITY SYSTEMS INC,323111,7922,,,,,NaN,...,,,NaN,1.80000,288880.0,0.978022,1.80000,1.81000,38,95.9
21,10257,2017-12-01,D L H HOLDINGS CORP,561320,8185,,,,,NaN,...,,,NaN,6.16000,3106.0,-0.019124,6.15000,6.27000,38,95.9
22,10258,2017-12-01,CELLDEX THERAPEUTICS INC,325413,8186,,,,,NaN,...,,,NaN,2.84000,232505.0,-0.053333,2.83000,2.84000,38,95.9
23,10294,2017-12-01,HAVERTY FURNITURE COS INC,442110,2089,,,,,NaN,...,,,NaN,-22.97500,13.0,-0.060327,22.45000,23.50000,38,95.9
24,10308,2017-12-01,TOMPKINS FINANCIAL CORP,551112,8228,,,,,NaN,...,,,NaN,81.35000,7919.0,-0.081414,81.35000,81.67000,38,95.9
25,10318,2017-12-01,BALCHEM CORP,325199,8237,2017-12-13,,2018-01-19,2017-12-27,0.0,...,,,NaN,80.60000,22546.0,-0.071617,80.59000,80.60000,38,95.9
26,10333,2017-12-01,XOMA CORP,325412,8254,,,,,NaN,...,,,NaN,35.60000,30545.0,0.178808,35.57000,35.60000,38,95.9
27,10355,2017-12-01,DAILY JOURNAL CORP,511110,8278,,,,,NaN,...,,,NaN,230.22000,354.0,-0.022960,223.34000,233.99001,38,95.9
28,10382,2017-12-01,ASTEC INDUSTRIES INC,336510,8299,,,,,NaN,...,,,NaN,58.50000,42802.0,0.056529,58.50000,58.51000,38,95.9
29,10397,2017-12-01,WERNER ENTERPRISES INC,484121,8317,2017-11-15,,2018-01-16,2018-01-02,0.0,...,,,NaN,38.65000,110833.0,0.013613,38.65000,38.70000,38,95.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234558,93367,2021-01-01,INVESCO E T F TRUST II,525990,52902,,,,,NaN,...,,,NaN,103.05000,2769.0,0.265221,102.79000,102.92000,38,79
234559,93368,2021-01-01,EAGLE BANCORP MONTANA INC,551111,53402,,,,,NaN,...,,,NaN,21.39000,5481.0,0.008011,21.03000,21.45000,38,79
234560,93369,2021-01-01,R1 R C M INC,561110,53403,,,,,NaN,...,,,NaN,25.23000,176236.0,0.050375,25.22000,25.23000,38,79
234561,93370,2021-01-01,BLACKSTONE SR FLTG RT TRM FD,525910,53404,,,,,NaN,...,,,NaN,14.64000,8869.0,0.029536,14.61000,14.64000,42,79
234562,93371,2021-01-01,CORMEDIX INC,325412,53357,,,,,NaN,...,,,NaN,8.75000,87395.0,0.177658,8.75000,8.80000,38,79
234563,93372,2021-01-01,DOUGLAS DYNAMICS INC,333120,53405,,,,,NaN,...,,,NaN,40.80000,15214.0,-0.046060,40.76000,40.80000,38,79
234564,93373,2021-01-01,EXPRESS INC,448120,53406,,,,,NaN,...,,,NaN,6.00000,10373409.0,5.593406,5.95000,5.99000,38,79
234565,93374,2021-01-01,FIRST AMERICAN FINL CORP NEW,524127,53407,,,,,NaN,...,,,NaN,52.29000,120590.0,0.012783,52.32000,52.33000,38,79
234566,93376,2021-01-01,ISHARES INC,525990,31600,,,,,NaN,...,,,NaN,71.78690,4232.0,-0.005705,71.47000,71.55000,39,79
234567,93377,2021-01-01,ISHARES TRUST,525990,37493,,,,,NaN,...,,,NaN,22.45000,166985.0,-0.041418,22.47000,22.48000,38,79
234568,93378,2021-01-01,ISHARES TRUST,525990,37493,,,,,NaN,...,,,NaN,48.22000,1086.0,-0.045148,48.15000,48.34000,38,79
234569,93379,2021-01-01,ISHARES TRUST,525990,37493,,,,,NaN,...,,,NaN,18.77000,65753.0,-0.013144,18.77000,18.86000,38,79
234570,93380,2021-01-01,JINKOSOLAR HOLDING CO LTD,334413,53409,,,,,NaN,...,,,NaN,61.99000,713486.0,0.001940,62.01000,62.10000,38,79
234571,93385,2021-01-01,SPDR SERIES TRUST,525990,39147,,,,,NaN,...,,,NaN,37.36000,7990.0,-0.014248,37.36000,37.42000,42,79
234572,93393,2021-01-01,GENMARK DIAGNOSTICS INC,339112,53419,,,,,NaN,...,,,NaN,13.81000,202692.0,-0.054110,13.80000,13.81000,38,79
234573,93397,2021-01-01,LIMONEIRA CO,115114,53423,,,,,NaN,...,,,NaN,15.97000,14516.0,-0.040841,15.96000,15.97000,38,79
234574,93401,2021-01-01,TELENAV INC,334511,53428,,,,,NaN,...,,,NaN,4.76000,81890.0,0.012766,4.76000,4.77000,38,79
234575,93415,2021-01-01,CLEARBRIDGE MLP & MIDSTR FD INC,525910,53433,,,,,NaN,...,,,NaN,18.24000,18344.0,0.087008,18.24000,18.29000,38,79
234576,93416,2021-01-01,EATON VANCE TAX MAN BUY WR ST FD,525990,53435,2021-01-04,,2021-01-29,2021-01-22,0.0,...,,,NaN,9.94000,7374.0,0.011192,9.84000,9.93000,38,79
234577,93419,2021-01-01,HUDSON PACIFIC PROPERTIES INC,531110,53437,,,,,NaN,...,,,NaN,23.44000,326182.0,-0.024147,23.42000,23.44000,38,79
234578,93421,2021-01-01,INVESCO E T F TRUST II,525990,52902,2021-01-15,,2021-01-29,2021-01-20,0.0,...,,,NaN,29.80000,5597.0,-0.013019,29.80000,29.89000,38,79
234579,93422,2021-01-01,Q E P RESOURCES INC,211120,53439,,,,,NaN,...,,,NaN,2.85000,951507.0,0.192469,2.83000,2.84000,38,79
234580,93423,2021-01-01,SIX FLAGS ENTERTAINMENT CORP,713110,53440,,,,,NaN,...,,,NaN,34.20000,322039.0,0.002933,34.19000,34.20000,38,79
234581,93424,2021-01-01,TEUCRIUM COMMODITY TRUST,523140,53441,,,,,NaN,...,,,NaN,16.88000,61550.0,0.083440,16.87000,16.88000,38,79
234582,93425,2021-01-01,UNITED STATES BRENT OIL FUND LP,523130,53442,,,,,NaN,...,,,NaN,13.74000,147159.0,0.066770,13.72000,13.73000,38,79
234583,93426,2021-01-01,VISHAY PRECISION GROUP INC,334416,53443,,,,,NaN,...,,,NaN,31.99000,14449.0,0.016201,32.00000,32.07000,38,79
234584,93427,2021-01-01,FABRINET,333314,53445,,,,,NaN,...,,,NaN,78.94000,30462.0,0.017399,78.94000,78.95000,38,79
234585,93429,2021-01-01,C B O E GLOBAL MARKETS INC,523210,53447,,,,,NaN,...,,,NaN,91.73000,136159.0,-0.014927,91.66000,91.73000,38,79
234586,93434,2021-01-01,S & W SEED CO,111998,53427,,,,,NaN,...,,,NaN,3.50000,26167.0,0.194539,3.47000,3.50000,38,79
234587,93436,2021-01-01,TESLA INC,336111,53453,,,,,NaN,...,,,NaN,793.53003,7038597.0,0.124506,793.21997,793.25000,38,79

In [9]:
#Ensure no errors in the returns column (there have been some instances where returns have taken on non-numeric values)
universe_df_with_external_factors["RET"] = pd.to_numeric(universe_df_with_external_factors["RET"], errors="coerce")

#Here, we select our required columns in proper order (see function documentation for more info) and get rid of extra columns that we will not use
universe_df_with_external_factors_filtered = universe_df_with_external_factors[["PERMNO","date","RET", "UMCSENT"]]

#Remove duplicate rows from universe (monthly returns) dataframe to avoid faulty data 
universe_df_with_external_factors_filtered = universe_df_with_external_factors_filtered.drop_duplicates()

#Convert consumer sentiment type to float
universe_df_with_external_factors_filtered["UMCSENT"] = universe_df_with_external_factors_filtered["UMCSENT"].astype(float)

display(universe_df_with_external_factors_filtered)

        PERMNO       date       RET  UMCSENT
0        10026 2017-12-01  0.007743     95.9
1        10028 2017-12-01 -0.104808     95.9
2        10032 2017-12-01 -0.028635     95.9
3        10044 2017-12-01  0.024296     95.9
4        10051 2017-12-01       NaN     95.9
5        10065 2017-12-01  0.010760     95.9
6        10066 2017-12-01       NaN     95.9
7        10104 2017-12-01 -0.036282     95.9
8        10107 2017-12-01  0.016277     95.9
9        10113 2017-12-01  0.056049     95.9
10       10138 2017-12-01  0.025068     95.9
11       10145 2017-12-01 -0.016671     95.9
12       10158 2017-12-01  0.011765     95.9
13       10200 2017-12-01  0.023413     95.9
14       10201 2017-12-01 -0.078431     95.9
15       10207 2017-12-01  0.020050     95.9
16       10220 2017-12-01 -0.031385     95.9
17       10232 2017-12-01  0.003879     95.9
18       10239 2017-12-01 -0.018443     95.9
19       10252 2017-12-01 -0.034801     95.9
20       10253 2017-12-01  0.978022     95.9
21       10257 2017-12-01 -0.019124     95.9
22       10258 2017-12-01 -0.053333     95.9
23       10294 2017-12-01 -0.060327     95.9
24       10308 2017-12-01 -0.081414     95.9
25       10318 2017-12-01 -0.071617     95.9
26       10333 2017-12-01  0.178808     95.9
27       10355 2017-12-01 -0.022960     95.9
28       10382 2017-12-01  0.056529     95.9
29       10397 2017-12-01  0.013613     95.9
...        ...        ...       ...      ...
234558   93367 2021-01-01  0.265221     79.0
234559   93368 2021-01-01  0.008011     79.0
234560   93369 2021-01-01  0.050375     79.0
234561   93370 2021-01-01  0.029536     79.0
234562   93371 2021-01-01  0.177658     79.0
234563   93372 2021-01-01 -0.046060     79.0
234564   93373 2021-01-01  5.593406     79.0
234565   93374 2021-01-01  0.012783     79.0
234566   93376 2021-01-01 -0.005705     79.0
234567   93377 2021-01-01 -0.041418     79.0
234568   93378 2021-01-01 -0.045148     79.0
234569   93379 2021-01-01 -0.013144     79.0
234570   93380 2021-01-01  0.001940     79.0
234571   93385 2021-01-01 -0.014248     79.0
234572   93393 2021-01-01 -0.054110     79.0
234573   93397 2021-01-01 -0.040841     79.0
234574   93401 2021-01-01  0.012766     79.0
234575   93415 2021-01-01  0.087008     79.0
234576   93416 2021-01-01  0.011192     79.0
234577   93419 2021-01-01 -0.024147     79.0
234578   93421 2021-01-01 -0.013019     79.0
234579   93422 2021-01-01  0.192469     79.0
234580   93423 2021-01-01  0.002933     79.0
234581   93424 2021-01-01  0.083440     79.0
234582   93425 2021-01-01  0.066770     79.0
234583   93426 2021-01-01  0.016201     79.0
234584   93427 2021-01-01  0.017399     79.0
234585   93429 2021-01-01 -0.014927     79.0
234586   93434 2021-01-01  0.194539     79.0
234587   93436 2021-01-01  0.124506     79.0

[233110 rows x 4 columns]

In [10]:
#Defining the factor model that takes a dataframe of the required columns (unique identifier, date/index column, returns columns, and a set of factors)
def olsfactormodel(df_attached, lookbackwindow:int, returnsvec:bool):

    #Assign passed dataframe to new dataframe
    df = df_attached.copy(deep=True)
    
    #We generate our list of unique tickers using the column in the unique identifier position (0, or leftmost column)
    uniqueTickerList = df.iloc[:,0].unique()
    
    #Initialize large df to drop results of regression for each security at each regression date
    containerdf = pd.DataFrame()
                
    #Set our lookback window to 24 periods (months in this case). This means that we will run a regression for each period (after the first 24 months) using the previous 24 months as data
    LookBack_Window=lookbackwindow
    
    #We will now create a new set of columns for the Beta and P-value for each of our factors. We will do this by iterating through each factor and columns for the beta coefficients
    factorlist = list(df.columns[3:])
    
    #For each factor, define an empty column to hold the corresponding coefficient
    for factor in factorlist: 
        df["Beta_" + factor] = 0


    #For each factor, define an empty column to hold the corresponding t-stat/p-value
    for factor in factorlist: 
        df["T-Stat_" + factor] = 0
    
    #Initialize global parameter(s) regardless of factor count
    df["R_squared"] = 0
    df["Constant B0"] = 0

    #For each identifier (ticker), generate a dataframe from the broader dataframe that 
    for ticker in uniqueTickerList:
        
        #For each unique identifier (ticker), we create a dataframe with observations from that particular identifier
        ticker_specific_universe_df = df.loc[df.iloc[:,0] == ticker]
        
        #We then sort our date/index column in position 1 to ensure our date is ascending from the earliest available
        ticker_specific_universe_df = ticker_specific_universe_df.sort_values(by= ticker_specific_universe_df.columns[1])

        #Shift our returns data back by one period. This way, we regress "t" factors to "t+1" returns, and our betas become forecasts
        ticker_specific_universe_df['RET'] = ticker_specific_universe_df['RET'].shift(-1)

        if returnsvec == True:
            ticker_specific_universe_df = ticker_specific_universe_df.tail(LookBack_Window+1)

        #For each lookback window span, train an OLS and collect the results
        for x in range(0, (len(ticker_specific_universe_df)-LookBack_Window)):
            
            # Define the independent variables (X) and dependent variable (Y). X's are defined by our factor columns and our returns are defined in our third left-most column (position 2)
            X = ticker_specific_universe_df[factorlist][x:x+LookBack_Window]
            Y = ticker_specific_universe_df[ticker_specific_universe_df.columns[2]][x:x+LookBack_Window]
    
            #Add a constant term to the independent variables, check impact
            X = sm.add_constant(X)
        
            #Fit the linear regression model
            model = sm.OLS(Y, X)
            results = model.fit()
            
            #Place our regression coefficients into their appropriate columns
            ticker_specific_universe_df.loc[ticker_specific_universe_df.index[x+LookBack_Window], "Constant B0"] = results.params[0]
            ticker_specific_universe_df.loc[ticker_specific_universe_df.index[x+LookBack_Window], "R_squared"] = results.rsquared
    
            #We do the same dynamically using our list of factors and placing into the appropriate factor column
            #Define an index (starting position for inserting regression params)
            i = 3 + len(factorlist) - 1
            
            for index in range(len(factorlist)):
                #increase our indices by one for each factor
                index+=1
                i+=1
                j = i+len(factorlist)
                
                ticker_specific_universe_df.loc[ticker_specific_universe_df.index[x+LookBack_Window], ticker_specific_universe_df.columns[i]] = results.params[index]
                ticker_specific_universe_df.loc[ticker_specific_universe_df.index[x+LookBack_Window], ticker_specific_universe_df.columns[j]] = results.pvalues[index]
         
        #Add ticker dataframe to larger container dataframe
        if returnsvec==1:
            containerdf = pd.concat([containerdf, ticker_specific_universe_df[ticker_specific_universe_df["date"]==np.max(ticker_specific_universe_df.date)]], ignore_index=True)
        else:
            containerdf = pd.concat([containerdf, ticker_specific_universe_df], ignore_index=True)        
    return containerdf

In [11]:
returnsdf = olsfactormodel(universe_df_with_external_factors_filtered,36,1)
display(returnsdf)

,PERMNO,date,RET,UMCSENT,Beta_UMCSENT,T-Stat_UMCSENT,R_squared,Constant B0
0,10026,2021-01-01,NaN,79.0,-0.001297,0.263077,0.036692,0.125338
1,10028,2021-01-01,NaN,79.0,-0.001177,0.811818,0.001690,0.190638
2,10032,2021-01-01,NaN,79.0,-0.001957,0.203816,0.047052,0.190723
3,10044,2021-01-01,NaN,79.0,-0.001440,0.565372,0.009816,0.115832
4,10051,2021-01-01,NaN,79.0,NaN,NaN,NaN,NaN
5,10065,2021-01-01,NaN,79.0,-0.001600,0.112461,0.072430,0.158780
6,10066,2021-01-01,NaN,79.0,NaN,NaN,NaN,NaN
7,10104,2021-01-01,NaN,79.0,-0.001308,0.215819,0.044693,0.127834
8,10107,2021-01-01,NaN,79.0,-0.000822,0.392767,0.021563,0.103280
9,10113,2021-01-01,NaN,79.0,-0.002550,0.027043,0.135730,0.236105
10,10138,2021-01-01,NaN,79.0,-0.001966,0.122620,0.068665,0.195083
11,10145,2021-01-01,NaN,79.0,-0.002258,0.079107,0.087908,0.218762
12,10158,2021-01-01,NaN,79.0,-0.004739,0.058516,0.101302,0.497711
13,10200,2021-01-01,NaN,79.0,0.000185,0.919658,0.000304,0.037337
14,10201,2021-01-01,NaN,79.0,-0.001668,0.260360,0.037104,0.165889
15,10207,2021-01-01,NaN,79.0,-0.002343,0.056060,0.103213,0.222397
16,10220,2021-01-01,NaN,79.0,-0.001056,0.521365,0.012198,0.097877
17,10232,2021-01-01,NaN,79.0,-0.000504,0.690162,0.004732,0.040442
18,10239,2021-01-01,NaN,79.0,-0.000790,0.599826,0.008182,0.065408
19,10252,2021-01-01,NaN,79.0,-0.000244,0.875793,0.000729,0.029515
20,10253,2021-01-01,NaN,79.0,0.001065,0.809050,0.001741,-0.134728
21,10257,2021-01-01,NaN,79.0,-0.004627,0.068308,0.094418,0.450460
22,10258,2021-01-01,NaN,79.0,-0.030457,0.015798,0.159561,2.896860
23,10294,2021-01-01,NaN,79.0,-0.006871,0.007064,0.194696,0.657439
24,10308,2021-01-01,NaN,79.0,-0.000298,0.806701,0.001785,0.026110
25,10318,2021-01-01,NaN,79.0,-0.000708,0.619045,0.007351,0.077227
26,10333,2021-01-01,NaN,79.0,-0.003234,0.374691,0.023246,0.319176
27,10355,2021-01-01,NaN,79.0,-0.002272,0.284304,0.033637,0.225675
28,10382,2021-01-01,NaN,79.0,-0.004043,0.030389,0.130533,0.377190
29,10397,2021-01-01,NaN,79.0,-0.000323,0.801259,0.001889,0.035456
...,...,...,...,...,...,...,...,...
6105,93373,2021-01-01,NaN,79.0,-0.021287,0.227082,0.042612,2.104089
6106,93374,2021-01-01,NaN,79.0,-0.001702,0.248887,0.038904,0.159467
6107,93376,2021-01-01,NaN,79.0,-0.002181,0.047437,0.110662,0.209982
6108,93377,2021-01-01,NaN,79.0,-0.002863,0.058451,0.101351,0.260965
6109,93378,2021-01-01,NaN,79.0,-0.002874,0.011843,0.172227,0.267236
6110,93379,2021-01-01,NaN,79.0,-0.002825,0.065667,0.096170,0.252669
6111,93380,2021-01-01,NaN,79.0,-0.007431,0.086707,0.083852,0.738246
6112,93385,2021-01-01,NaN,79.0,-0.001038,0.015776,0.159621,0.096957
6113,93393,2021-01-01,NaN,79.0,-0.002836,0.683314,0.004955,0.329998
6114,93397,2021-01-01,NaN,79.0,-0.002188,0.165266,0.055843,0.198278
6115,93401,2021-01-01,NaN,79.0,0.001020,0.737115,0.003358,-0.081675
6116,93415,2021-01-01,NaN,79.0,-0.004145,0.305859,0.030808,0.381909
6117,93416,2021-01-01,NaN,79.0,-0.001253,0.214207,0.045001,0.125542
6118,93419,2021-01-01,NaN,79.0,-0.000466,0.762322,0.002726,0.040445
6119,93421,2021-01-01,NaN,79.0,-0.001067,0.023153,0.142636,0.101083
6120,93422,2021-01-01,NaN,79.0,-0.011555,0.134330,0.064715,1.111827
6121,93423,2021-01-01,NaN,79.0,-0.005297,0.113177,0.072153,0.490050
6122,93424,2021-01-01,NaN,79.0,-0.002102,0.009761,0.180673,0.193923
6123,93425,2021-01-01,NaN,79.0,-0.005756,0.020383,0.148291,0.532309
6124,93426,2021-01-01,NaN,79.0,-0.002278,0.275953,0.034805,0.220737
6125,93427,2021-01-01,NaN,79.0,0.000611,0.770722,0.002532,-0.016768
6126,93429,2021-01-01,NaN,79.0,-0.000423,0.774605,0.002444,0.032815
6127,93434,2021-01-01,NaN,79.0,-0.003422,0.197010,0.048462,0.320483
6128,93436,2021-01-01,NaN,79.0,-0.009104,0.023252,0.142447,0.929063
6129,17273,2021-01-01,NaN,79.0,NaN,NaN,NaN,NaN
6130,17287,2021-01-01,NaN,79.0,NaN,NaN,NaN,NaN
6131,17674,2021-01-01,NaN,79.0,NaN,NaN,NaN,NaN
6132,17513,2021-01-01,NaN,79.0,0.000000,0.000000,0.000000,0.000000
6133,17706,2021-01-01,NaN,79.0,0.000000,0.000000,0.000000,0.000000
6134,17779,2021-01-01,NaN,79.0,0.000000,0.000000,0.000000,0.000000